name: flutter3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  stacked: ^2.3.15+1
  stacked_core: ^1.2.4
  stacked_hooks: ^0.2.2

  # navigation
  auto_route: ^5.0.1
  stacked_services: ^0.9.5

  # inversion of control
  get_it: ^7.2.0
  injectable: ^1.4.0
  flutter_hooks: ^0.18.5+1
  observable_ish: ^4.0.6
  http: ^0.13.5
  animations: ^2.0.4
  json_annotation: ^4.6.0

  # device
  settings_ui: ^2.0.2
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15

  # localization
  easy_localization: ^3.0.1

  logger: ^1.1.0
  theme_mode_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.8
  stacked_generator:
  json_serializable:

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf